// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vavvekmipsmbudvvznyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdnZla21pcHNtYnVkdnZ6bnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNzU3NTIsImV4cCI6MjA4Mzg1MTc1Mn0.ZRh8mjJA1OSZVcq0I9Wr0wNFT00SEqoC2-H4EFWgZxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});